version: "3.5"

services:
   app1:
    build :
      context: ./
    image: sample-port-app
    container_name: app1
    ports: ["3000"]
    environment :
     - NODENUMBER=1
    hostname: app1
    networks:
     sample-app-used-port:
      ipv4_address: 172.10.213.2

   app2:
    build :
      context: ./
    image: sample-port-app
    container_name: app2
    ports: ["3000"]
    environment :
     - NODENUMBER=2
    hostname: app2
    networks:
     sample-app-used-port:
      ipv4_address: 172.10.213.3

networks:
 sample-app-used-port:
  name : sample_app_used_port
  driver: bridge
  ipam:
   driver: default
   config: 
     - subnet: 172.10.213.0/24
